### ISSUE TITLE
preprocess_info.infopkl

### ISSUE THREAD

**Issue by HireTheHero** [AITRICS/EEG_real_time_seizure_detection#2]
Trying to follow your ReadMe.
In preprocessing script `preprocess_info.infopkl` is required, which I couldn't find in original [TUSZ](https://isip.piconepress.com/projects/tuh_eeg/downloads/tuh_eeg_seizure/) dataset or your repo.
Could you help me find it?
```
Traceback (most recent call last):
  File "/path/to/eeg/eeg_real_time_seizure_detection/1_preprocess.py", line 1108, in <module>
    main(args)
  File "/path/to/eeg/eeg_real_time_seizure_detection/1_preprocess.py", line 1017, in main
    with open(data_file_directory + "/preprocess_info.infopkl", "wb") as pkl:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/data/dataset-tuh_task-binary_datatype-train_v6/preprocess_info.infopkl'

```

**Comment by HireTheHero** [comment]
Oh, it's writing row not reading one. Let me try my fix and reopen this issue if needed
