### ISSUE TITLE
Encountering a problem when running 1_preprocess.py

### ISSUE THREAD

**Issue by ZhyCong** [AITRICS/EEG_real_time_seizure_detection#5]
Dear source code provider:
It seems that every subject will look for a .tse file or a .tse_bi file, but in fact most of the data in the dataset does not have a .tse file, so the following error will be reported in 1_preprocess.py
```
################ Preprocess begins... ################

8
  0%|                                             | 0/1832 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/d/script/23-EEG_real_time_seizure_detection/1_preprocess2.py", line 312, in generate_training_data_leadwise_tuh_train_final
    label_file = open(file_name + "." + GLOBAL_DATA['label_type'], 'r') # EX) 00007235_s003_t003.tse or 00007235_s003_t003.tse_bi
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/f/data/04_tuh_eeg/edf/dev/aaaaaajy/s002_2003_07_21/01_tcp_ar/aaaaaajy_s002_t001.tse_bi'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/script/23-EEG_real_time_seizure_detection/1_preprocess2.py", line 869, in <module>
    main(args)
  File "/mnt/d/script/23-EEG_real_time_seizure_detection/1_preprocess2.py", line 827, in main
    run_multi_process(generate_training_data_leadwise_tuh_train_final, edf_list, n_processes=cpu_num)
  File "/mnt/d/script/23-EEG_real_time_seizure_detection/builder/utils/process_util.py", line 13, in run_multi_process
    for r in tqdm(pool.imap_unordered(f, l), total=len(l), ncols=75):
  File "/home/user/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/f/data/04_tuh_eeg/edf/dev/aaaaaajy/s002_2003_07_21/01_tcp_ar/aaaaaajy_s002_t001.tse_bi'

Process finished with exit code 1

```

**Comment by TacticalLettuce** [comment]
You are not using the correct dataset. Probably you are using the 2.0.0 while this dataset works on 1.5.2. You may have to download the older version
